name: app

type: php:8.0

runtime:
    extensions:
        - xsl
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_pgsql


variables:
    php-ext:
        apcu: version
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 512

relationships:
    database: "db:postgresql"

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)

        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

workers:
    messages:
        commands:
            start: symfony console messenger:consume async -vv --time-limit=3600 --memory-limit=128M
